services:
  cobalt:
    container_name: cobalt-duckdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - type: bind
        source: ./model
        target: /model